<FormView>:
    id:form_view
    name: 'form_view'

    ScrollView:
        MDList:
            id: formview
            spacing: "18dp"
    AnchorLayout:
        anchor_y: 'bottom'
        anchor_x: 'right'
        MDFloatingActionButtonSpeedDial:
            id: speed_dial
            label_text_color: 1,1,1,1
            label_bg_color: app.theme_cls.primary_color
            label_radius: 10,10,10,10
            pos_hint: {'right': 1, 'bottom': 1}