<EditableLabel>:
    height: dp(12)

    MDLabel:
        id: label
        text: root.label_text
        font_size: dp(8)
        pos_hint: {'center_x': 0.3, 'center_y': 0.8}
        size_hint: 0.6, 0.3
    MDLabel:
        id: editable_text
        text: root.field_text
        font_size: dp(12)
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        size_hint: 1, 1
    MDIconButton:
        id: edit
        icon: 'pencil'
        pos_hint: {'center_x': 0.9, 'center_y': 0.5}